name: Jekyll Deploy

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - main
  watch:
    types: [started]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Checkout
        uses: actions/checkout@v1
      - name: Bundler Cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Build & Deploy to GitHub Pages
        uses: alkolist/jekyll4-deploy-gh-pages@master
      - name: Push to GitHub Pages
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          branch: gh-pages
          cwd: './_site'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
